### PR TITLE
Added-controllers-spec

### PR DESCRIPTION
**Pull request by moise10r**
### In this project, I did the following things:

- Add RSpec as a gem to your project.
- Create a Request spec file for all your controllers.
- Make sure that for each action you check:
   - If response status was correct.
   - If a correct template was rendered.
   - If the response body includes correct placeholder text.

### CODE REVIEW

**Review by oxenprogrammer — CHANGES_REQUESTED** [review]
Hi @moise10r, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Required Changes ♻️
- [ ] Currently both the test and the app is not running probably because of a missing JavaScript dependency `Webpacker`. Please include the steps on how to install it in the `README` file. However good effort so far.

webpacker-missing


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by moise10r** [comment]
Hello @oxenprogrammer, I'm a little bit confused about what you got on your end.
I tried to run again the application on my side, it runs and the webpacker is installed correctly.

- you can see the image below:
Screenshot from 2021-10-29 01-28-01

- And the image of the running application:
Screenshot from 2021-10-29 01-28-51

**Comment by moise10r** [comment]
### Note to the following reviewer:

   - The project was working on my end without adding the webpacker module but if you find an issue as the previous reviewer, try to do the following steps:
     - 
```sh
# run 
bundle install
# And then run
bin/rails webpacker:install

```

**Comment by Davidosky007** [comment]
## Hi @moise10r 👋, 

## Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 
doing-good-gif



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by moise10r** [comment]
Thank you for taking the time to review this PR

**Pull request merged**
